export const GAME_CONFIG = {
  npcCount: 3,
  seatOrder: [1, 2, 0, 3],
  startingChips: 1200,
  difficulty: "hard",
  smallBlind: 10,
  bigBlind: 20,
  blindIncreaseHands: 6,
  allowRebuys: true,
  maxRaisesPerRound: 2,
  autoStartHands: true,
  preDealDelayMs: 650,
  handTransitionDelayMs: 2000,
  dealDelayMs: 340,
  dealAnimationMs: 260,
  dealTiltMaxDeg: 7,
  dealSettleBufferMs: 90,
  npcThinkDelayMs: 900,
  allInOddsTrials: 1400,
  announcementDurationMs: 2600,
};
